---
- hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Install OpenSCAP
      apt:
        name: openscap-utils
        state: latest

    - name: Download ISO 27001
      get_url:
        url: https://exemplo.com/iso27001.xml
        dest: /tmp/iso27001.xml

    - name: Run OpenSCAP evaluation
      command: oscap xccdf eval --profile iso27001 --results /tmp/iso27001-results.xml /tmp/iso27001.xml
      register: oscap_output

    - name: Generate HTML report
      command: oscap xccdf generate report --output /tmp/iso27001-report.html /tmp/iso27001-results.xml
      when: oscap_output.rc == 0

    - name: Send HTML report via email
      mail:
        subject: "ISO 27001 Compliance Report"
        body: "Please find attached the compliance report."
        to: user@example.com
        attach:
          - /tmp/iso27001-report.html
      when: oscap_output.rc == 0
